version: "2"

linters:
  enable:
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    gocyclo:
      min-complexity: 35

