[tools]
go = "1.26.5"
hugo-extended = "latest"
"golangci-lint" = "latest"
swag = "1.16.6"
task = "3"
"go:github.com/air-verse/air" = "latest"
"aqua:casey/just" = "latest"
"aqua:anchore/grype" = "latest"
