/** Grouped IANA timezone names for the timezone picker. */
export const timezoneGroups = [
  {
    label: 'Common',
    zones: [
      'UTC',
      'US/Eastern',
      'US/Central',
      'US/Mountain',
      'US/Pacific',
      'Europe/London',
      'Europe/Berlin',
      'Asia/Tokyo',
      'Australia/Sydney',
    ],
  },
  {
    label: 'Africa',
    zones: [
      'Africa/Cairo',
      'Africa/Casablanca',
      'Africa/Johannesburg',
      'Africa/Lagos',
      'Africa/Nairobi',
    ],
  },
  {
    label: 'America',
    zones: [
      'America/Anchorage',
      'America/Argentina/Buenos_Aires',
      'America/Bogota',
      'America/Chicago',
      'America/Denver',
      'America/Halifax',
      'America/Lima',
      'America/Los_Angeles',
      'America/Mexico_City',
      'America/New_York',
      'America/Phoenix',
      'America/Santiago',
      'America/Sao_Paulo',
      'America/St_Johns',
      'America/Toronto',
      'America/Vancouver',
    ],
  },
  {
    label: 'Asia',
    zones: [
      'Asia/Bangkok',
      'Asia/Colombo',
      'Asia/Dhaka',
      'Asia/Dubai',
      'Asia/Ho_Chi_Minh',
      'Asia/Hong_Kong',
      'Asia/Istanbul',
      'Asia/Jakarta',
      'Asia/Jerusalem',
      'Asia/Karachi',
      'Asia/Kolkata',
      'Asia/Kuala_Lumpur',
      'Asia/Manila',
      'Asia/Riyadh',
      'Asia/Seoul',
      'Asia/Shanghai',
      'Asia/Singapore',
      'Asia/Taipei',
      'Asia/Tehran',
      'Asia/Tokyo',
    ],
  },
  {
    label: 'Australia',
    zones: [
      'Australia/Adelaide',
      'Australia/Brisbane',
      'Australia/Darwin',
      'Australia/Hobart',
      'Australia/Melbourne',
      'Australia/Perth',
      'Australia/Sydney',
    ],
  },
  {
    label: 'Europe',
    zones: [
      'Europe/Amsterdam',
      'Europe/Athens',
      'Europe/Belgrade',
      'Europe/Berlin',
      'Europe/Brussels',
      'Europe/Bucharest',
      'Europe/Budapest',
      'Europe/Copenhagen',
      'Europe/Dublin',
      'Europe/Helsinki',
      'Europe/Kiev',
      'Europe/Lisbon',
      'Europe/London',
      'Europe/Madrid',
      'Europe/Moscow',
      'Europe/Oslo',
      'Europe/Paris',
      'Europe/Prague',
      'Europe/Rome',
      'Europe/Stockholm',
      'Europe/Vienna',
      'Europe/Warsaw',
      'Europe/Zurich',
    ],
  },
  {
    label: 'Pacific',
    zones: [
      'Pacific/Auckland',
      'Pacific/Fiji',
      'Pacific/Guam',
      'Pacific/Honolulu',
    ],
  },
]

/** Flat list of all timezone names. */
export const allTimezones = timezoneGroups.flatMap(g => g.zones)
